import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { getCssText } from "../styles";
import { globalStyles } from "@/styles/global";
import logoImg from "../assets/logo.svg";
import Image from "next/image";
import { Container, Header } from "../styles/pages/app";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  globalStyles();

  return (
    <html lang="en">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </head>
      <body className={roboto.className}>
        <Container>
          <Header>
            <Image src={logoImg} alt="" height={52} width={130} priority />
          </Header>
          {children}
        </Container>
      </body>
    </html>
  );
}
